### ISSUE TITLE
Update to 1.4.2 fails

### ISSUE THREAD

**Issue by PiotrRozenfeld** [ibiza240/MTGAHelper-Windows-Client#14]
Attempt to update app fails. Log below. 

I attempted to reinstall and then the installer complained about missing .NET Core depenency.
It now works for me - reporting for others that may be experiencing the same issues

17 12:24:40 [INF] () C:\Users\Piotr\AppData\Local\Temp\.net\MTGAHelper.Tracker\t3ulj53x.aly
17 12:24:43 [ERR] () Error at startup:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.ServicePoint, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.ServicePoint, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)

   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at MTGAHelper.Tracker.WPF.App.MustDownloadNewVersion()
   at MTGAHelper.Tracker.WPF.App.CheckForUpdate()
   at MTGAHelper.Tracker.WPF.App.StartApp()

**Comment by ibiza240** [comment]
Thanks for reporting! Reinstalling was the right thing to do :) sorry for the inconvenience
