### ISSUE TITLE
Failed to apply patch to file: L"MTGA.exe"

### ISSUE THREAD

**Issue by ClintonBrown** [ibiza240/MTGAHelper-Windows-Client#5]
OS: Linux Mint 19.02

Found out about mtgaup today and decided to give it a try since the Lutris version of MTGA needs an update. Getting some errors when running `mtgaup`, also does not work with `mtgaup -i`, here is the terminal output from both of these as well as the `mtgaup --help` so you can see the environment variables:

```
clint@mishima-zaibatsu ~$ mtgaup
Defaulting to patch binary, if available.
Found patch binary https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1810.735881/MTGAPatch_0.1.1810.735881.msp
Download of /home/clint/MTGAPatch_0.1.1810.735881.msp finished.
(node:26926) UnhandledPromiseRejectionWarning: Error: Command failed: /home/clint/.local/share/lutris/runners/wine/tkg-unity-4.5-x86_64/bin/wine msiexec /p "/home/clint/MTGAPatch_0.1.1810.735881.msp"
000b:fixme:winediag:start_process Wine Staging 4.5 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0023:fixme:plugplay:build_report_descriptor Clamping joystick to 6 axis
0023:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0023:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0009:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0009:fixme:msi:is_uninstallable check other criteria
0039:fixme:advapi:ParseStringSidToSid String constant not supported: L"CY"
0039:fixme:advapi:ParseStringSidToSid String constant not supported: L"IS"
0009:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0
0009:fixme:ole:CoCreateInstanceEx no instance created for interface {9edde9e7-8dee-47ea-99df-e6faf2ed44bf} of class {389ea17b-5078-4cde-b6ef-25c15175c751}, hres is 0x80004005
0009:err:olepicture:OleLoadPicture IPersistStream_Load failed
0009:err:msi:msi_load_picture failed to load picture
0009:err:msi:msi_dialog_bitmap_control Failed to load bitmap L"DialogBitMap.png"
0009:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0
0009:fixme:ole:CoCreateInstanceEx no instance created for interface {9edde9e7-8dee-47ea-99df-e6faf2ed44bf} of class {389ea17b-5078-4cde-b6ef-25c15175c751}, hres is 0x80004005
0009:err:olepicture:OleLoadPicture IPersistStream_Load failed
0009:err:msi:msi_load_picture failed to load picture
0009:err:msi:msi_dialog_bitmap_control Failed to load bitmap L"DialogBitMap.png"
0009:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0
0009:fixme:ole:CoCreateInstanceEx no instance created for interface {9edde9e7-8dee-47ea-99df-e6faf2ed44bf} of class {389ea17b-5078-4cde-b6ef-25c15175c751}, hres is 0x80004005
0009:err:olepicture:OleLoadPicture IPersistStream_Load failed
0009:err:msi:msi_load_picture failed to load picture
0009:err:msi:msi_dialog_bitmap_control Failed to load bitmap L"FullHeader.png"
0009:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0
0009:fixme:ole:CoCreateInstanceEx no instance created for interface {9edde9e7-8dee-47ea-99df-e6faf2ed44bf} of class {389ea17b-5078-4cde-b6ef-25c15175c751}, hres is 0x80004005
0009:err:olepicture:OleLoadPicture IPersistStream_Load failed
0009:err:msi:msi_load_picture failed to load picture
0009:err:msi:msi_dialog_bitmap_control Failed to load bitmap L"FullHeader.png"
0045:fixme:advapi:ParseStringSidToSid String constant not supported: L"CY"
0045:fixme:advapi:ParseStringSidToSid String constant not supported: L"IS"
Can't recognize 'C:\users\clint\Temp\{9BE392DA-D71C-4525-8CDC-2CD1F94545A9}.bat' as an internal or external command, or batch script.
0009:fixme:mspatcha:ApplyPatchToFileW stub - L"C:\\users\\clint\\Temp\\msi269.tmp", L"C:\\Program Files (x86)\\Wizards of the Coast\\MTGA\\MTGA.exe", L"C:\\users\\clint\\Temp\\msi275.tmp", 00000000
0009:err:msi:ACTION_PatchFiles Failed to apply patch to file: L"MTGA.exe"
0009:err:msi:execute_script Execution of script 0 halted; action L"PatchFiles" returned 1603
0009:err:msi:ITERATE_Actions Execution halted, action L"InstallExecute" returned 1603
0009:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0009:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0009:err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
0009:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0
0009:fixme:ole:CoCreateInstanceEx no instance created for interface {9edde9e7-8dee-47ea-99df-e6faf2ed44bf} of class {389ea17b-5078-4cde-b6ef-25c15175c751}, hres is 0x80004005
0009:err:olepicture:OleLoadPicture IPersistStream_Load failed
0009:err:msi:msi_load_picture failed to load picture
0009:err:msi:msi_dialog_bitmap_control Failed to load bitmap L"DialogBitMap.png"

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:26926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26926) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
clint@mishima-zaibatsu ~$ mtgaup -i
Found installer binary https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1810.735881/MTGAInstaller_0.1.1810.735881.msi
Download of /home/clint/MTGAInstaller_0.1.1810.735881.msi finished.
(node:27229) UnhandledPromiseRejectionWarning: Error: Command failed: /home/clint/.local/share/lutris/runners/wine/tkg-unity-4.5-x86_64/bin/wine msiexec /i "/home/clint/MTGAInstaller_0.1.1810.735881.msi"
000b:fixme:winediag:start_process Wine Staging 4.5 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0023:fixme:plugplay:build_report_descriptor Clamping joystick to 6 axis
0023:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0023:err:hid:parse_descriptor Unknown (bTag: 0x0, bType: 0x0)
0009:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:27229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
clint@mishima-zaibatsu ~$ mtgaup --help
Usage: mtgaup 
This program, when called with no argument, will do the following:

  1. Fetch a WOTC endpoint containing URLs pointing to latest msp (or msi) binaries.
  2. Download, given user provided options, the preferred binary.
  3. Install the chosen binary with `wine msiexec'.

ENVIRONMENT VARIABLES
  MTGA_WINE_PREFIX is set to "/home/clint/Games/magic-the-gathering-arena"
  MTGA_WINE_BINARY is set to "/home/clint/.local/share/lutris/runners/wine/tkg-unity-4.5-x86_64/bin/wine"
```

Thanks for your work on this and any help you can provide.

**Comment by ibiza240** [comment]
Hi @ClintonBrown !

Are you sure this is on the good github project? I am not aware what mtgaup is...

**Comment by ClintonBrown** [comment]
Sorry I had multiple github projects open and posted this to the wrong one, closing.
